---
language: ruby

url_to_dependency_map:
  - match: node-v?(\d+\.\d+\.\d+)
    name: node
    version: $1
  - match: ruby_versions
    name: ruby_versions
    version: 0
  - match: openjdk7-latest
    name: openjdk7-latest
    version: 0
  - match: openjdk(\d+\.\d+\.\d+_\d+)
    name: openjdk
    version: $1

dependencies:
  - name: node
    version: 0.4.7
    uri: https://pivotal-buildpacks.s3.amazonaws.com/ruby/binaries/lucid64/node-0.4.7.tgz
    md5: 97eb2c31d883eb577783d17fb7d3e2e9
    cf_stacks:
      - lucid64
      - cflinuxfs2
  - name: node
    version: 0.10.30
    uri: https://pivotal-buildpacks.s3.amazonaws.com/ruby/binaries/lucid64/node-v0.10.30-linux-x64.tar.gz
    md5: e96aebef3cc0feaca0e9a7b73740ed01
    cf_stacks:
      - lucid64
      - cflinuxfs2
  - name: bundler
    version: 1.6.3
    uri: https://pivotal-buildpacks.s3.amazonaws.com/ruby/binaries/lucid64/bundler-1.6.3.tgz
    md5: 2f3f3a8581be58d6d6d71ec63d390e09
    cf_stacks:
      - lucid64
      - cflinuxfs2
  - name: ruby_versions
    version: 0
    uri: https://pivotal-buildpacks.s3.amazonaws.com/ruby/binaries/lucid64/ruby_versions.yml
    md5: 087ab6decfe4dd69027cf1c4bb14500b
    cf_stacks:
      - lucid64
      - cflinuxfs2
  - name: ruby
    version: 2.2.0
    uri: https://pivotal-buildpacks.s3.amazonaws.com/ruby/binaries/lucid64/ruby-2.2.0.tgz
    md5: 47e892bbaa2b08cf3c522a38c4c6755c
    cf_stacks:
      - lucid64
  - name: ruby
    version: 2.2.0
    uri: https://pivotal-buildpacks.s3.amazonaws.com/ruby/binaries/cflinuxfs2/ruby-2.2.0.tgz
    md5: ce0f6aebcc2d81b2dc7b0c34b6bf6570
    cf_stacks:
      - cflinuxfs2
  - name: ruby
    version: 2.1.4
    uri: https://pivotal-buildpacks.s3.amazonaws.com/ruby/binaries/lucid64/ruby-2.1.4.tgz
    md5: 2f98c1a85a79d852954af6feba397ec9
    cf_stacks:
      - lucid64
  - name: ruby
    version: 2.1.3
    uri: https://pivotal-buildpacks.s3.amazonaws.com/ruby/binaries/lucid64/ruby-2.1.3.tgz
    md5: f50897ce36b78a369008030f41668539
    cf_stacks:
      - lucid64
  - name: ruby
    version: 2.1.2
    uri: https://pivotal-buildpacks.s3.amazonaws.com/ruby/binaries/lucid64/ruby-2.1.2.tgz
    md5: 643818a5d0f969620c70301858120c66
    cf_stacks:
      - lucid64
  - name: ruby
    version: 2.1.1
    uri: https://pivotal-buildpacks.s3.amazonaws.com/ruby/binaries/lucid64/ruby-2.1.1.tgz
    md5: dd597c3fc9249a23e691b47be6da1066
    cf_stacks:
      - lucid64
  - name: ruby
    version: 2.1.0
    uri: https://pivotal-buildpacks.s3.amazonaws.com/ruby/binaries/lucid64/ruby-2.1.0.tgz
    md5: e13ab33d4ab8fce52067471adab770e6
    cf_stacks:
      - lucid64
  - name: ruby
    version: 2.1.4
    uri: https://pivotal-buildpacks.s3.amazonaws.com/ruby/binaries/cflinuxfs2/ruby-2.1.4.tgz
    md5: 971aad5cd68b8cbad8f96211549fcb8c
    cf_stacks:
      - cflinuxfs2
  - name: ruby
    version: 2.1.3
    uri: https://pivotal-buildpacks.s3.amazonaws.com/ruby/binaries/cflinuxfs2/ruby-2.1.3.tgz
    md5: db0610016d0f6065eb20ba49a95f3f66
    cf_stacks:
      - cflinuxfs2
  - name: ruby
    version: 2.1.2
    uri: https://pivotal-buildpacks.s3.amazonaws.com/ruby/binaries/cflinuxfs2/ruby-2.1.2.tgz
    md5: d6c11d37cd5e662b1e306d8c663a885a
    cf_stacks:
      - cflinuxfs2
  - name: openjdk
    version: 1.7.0_25
    uri: https://pivotal-buildpacks.s3.amazonaws.com/ruby/binaries/lucid64/openjdk1.7.0_25.tar.gz
    md5: 48549e234885241b2f745f88313af022
    cf_stacks:
      - lucid64
      - cflinuxfs2
  - name: openjdk7-latest
    version: 0
    uri: https://pivotal-buildpacks.s3.amazonaws.com/ruby/binaries/lucid64/openjdk7-latest.tar.gz
    md5: fdb9c737826ad97ae2160e2af4fb4be6
    cf_stacks:
      - lucid64

exclude_files:
  - .git/
  - .gitignore
  - .gitmodules
  - repos/
  - spec/
  - cf_spec/
  - log/
  - test/
  - cf.Gemfile
  - cf.Gemfile.lock
  - bin/package
  - buildpack-packager/
  - ruby_buildpack-*v*.zip

