---
language: ruby

url_to_dependency_map:
  - match: node-v?(\d+\.\d+\.\d+)
    name: node
    version: $1
  - match: ruby_versions
    name: ruby_versions
    version: 0

dependencies:
  - name: node
    version: 0.4.7
    uri: https://pivotal-buildpacks.s3.amazonaws.com/ruby/binaries/lucid64/node-0.4.7.tgz
    md5: 97eb2c31d883eb577783d17fb7d3e2e9
    cf_stacks:
      - lucid64
      - cflinuxfs2
  - name: node
    version: 0.10.30
    uri: https://pivotal-buildpacks.s3.amazonaws.com/ruby/binaries/lucid64/node-v0.10.30-linux-x64.tar.gz
    md5: e96aebef3cc0feaca0e9a7b73740ed01
    cf_stacks:
      - lucid64
      - cflinuxfs2
  - name: bundler
    version: 1.6.3
    uri: https://pivotal-buildpacks.s3.amazonaws.com/ruby/binaries/lucid64/bundler-1.6.3.tgz
    md5: 2f3f3a8581be58d6d6d71ec63d390e09
    cf_stacks:
      - lucid64
      - cflinuxfs2
  - name: ruby_versions
    version: 0
    uri: https://pivotal-buildpacks.s3.amazonaws.com/ruby/binaries/lucid64/ruby_versions.yml
    md5: 087ab6decfe4dd69027cf1c4bb14500b
    cf_stacks:
      - lucid64
      - cflinuxfs2

exclude_files:
  - .git/
  - .gitignore
  - .gitmodules
  - repos/
  - spec/
  - cf_spec/
  - log/
  - test/
  - cf.Gemfile
  - cf.Gemfile.lock
  - bin/package
  - buildpack-packager/
  - ruby_buildpack-*v*.zip

