---
language: ruby
rvm:
- 2.0.0
- 1.8.7
- 1.9.2
- 1.9.3
- jruby-18mode
- jruby-19mode
- rbx-19mode

before_script: bundle exec rake hatchet:setup_travis

# Run tests in parallel
script: bundle exec parallel_rspec -n 7 spec/

env:
  global:
  - HATCHET_RETRIES=3
  - IS_RUNNING_ON_TRAVIS=true